<?php

/*
 * Rule paranoia levels:
 *
 * low    - highest-confidence rules for apps with low false-positive tolerance
 * medium - default balanced rules
 * high   - more aggressive rules for apps that can tolerate more review/blocking
 * strict - most aggressive rules and edge-case probes
 *
 * Fireline runs rules at or below the configured paranoia_level.
 */

return [
    [
        'id' => 'SQL_UNION_SELECT',
        'type' => 'keyword',
        'pattern' => 'union select',
        'score' => 12,
        'category' => 'sqli',
        'paranoia' => 'low',
        'explanation' => 'Detects UNION SELECT SQL injection attempts.',
        'examples' => ['1 union select password from users'],
        'false_positives' => ['Documentation discussing UNION SELECT syntax'],
    ],
    [
        'id' => 'SQL_INFORMATION_SCHEMA',
        'type' => 'keyword',
        'pattern' => 'information_schema',
        'score' => 10,
        'category' => 'sqli',
        'paranoia' => 'medium',
        'explanation' => 'Detects database schema enumeration attempts.',
        'examples' => ['select table_name from information_schema.tables'],
        'false_positives' => ['Database administration tools'],
    ],
    [
        'id' => 'SQL_SLEEP',
        'type' => 'keyword',
        'pattern' => 'sleep(',
        'score' => 10,
        'category' => 'sqli',
        'paranoia' => 'medium',
        'explanation' => 'Detects time-based SQL injection probes.',
        'examples' => ['sleep(5)'],
        'false_positives' => ['Code snippets submitted in developer tools'],
    ],
    [
        'id' => 'XSS_SCRIPT_TAG',
        'type' => 'keyword',
        'pattern' => '<script',
        'score' => 20,
        'category' => 'xss',
        'paranoia' => 'low',
        'explanation' => 'Detects script tag injection.',
        'examples' => ['<script>alert(1)</script>'],
        'false_positives' => ['HTML tutorial submissions'],
    ],
    [
        'id' => 'XSS_JAVASCRIPT_SCHEME',
        'type' => 'keyword',
        'pattern' => 'javascript:',
        'score' => 12,
        'category' => 'xss',
        'paranoia' => 'medium',
        'explanation' => 'Detects JavaScript URL scheme injection.',
        'examples' => ['javascript:alert(1)'],
        'false_positives' => ['Documentation about JavaScript URLs'],
    ],
    [
        'id' => 'XSS_EVENT_HANDLER',
        'type' => 'keyword',
        'pattern' => 'onerror=',
        'score' => 12,
        'category' => 'xss',
        'paranoia' => 'high',
        'explanation' => 'Detects inline browser event handler payloads.',
        'examples' => ['<img src=x onerror=alert(1)>'],
        'false_positives' => ['HTML examples'],
    ],
    [
        'id' => 'SHELL_BIN_SH',
        'type' => 'keyword',
        'pattern' => '/bin/sh',
        'score' => 17,
        'category' => 'shell',
        'paranoia' => 'low',
        'explanation' => 'Detects shell execution probes.',
        'examples' => ['cmd=/bin/sh'],
        'false_positives' => ['Server administration forms'],
    ],
    [
        'id' => 'LFI_ETC_PASSWD',
        'type' => 'keyword',
        'pattern' => '/etc/passwd',
        'score' => 14,
        'category' => 'lfi',
        'paranoia' => 'low',
        'explanation' => 'Detects common Linux file disclosure probes.',
        'examples' => ['file=/etc/passwd'],
        'false_positives' => ['Security training content'],
    ],
    [
        'id' => 'PHP_STREAM_FILTER',
        'type' => 'keyword',
        'pattern' => 'php://filter',
        'score' => 35,
        'category' => 'lfi',
        'paranoia' => 'low',
        'explanation' => 'Detects PHP stream wrapper file disclosure probes.',
        'examples' => ['file=php://filter/convert.base64-encode/resource=index.php'],
        'false_positives' => ['PHP stream wrapper documentation'],
    ],
    [
        'id' => 'SCANNER_SQLMAP',
        'type' => 'keyword',
        'pattern' => 'sqlmap',
        'score' => 25,
        'category' => 'scanner',
        'paranoia' => 'medium',
        'explanation' => 'Detects common sqlmap scanner fingerprints.',
        'examples' => ['User-Agent: sqlmap/1.8'],
        'false_positives' => ['Security tool documentation'],
    ],
    [
        'id' => 'SCANNER_ACUNETIX',
        'type' => 'keyword',
        'pattern' => 'acunetix',
        'score' => 25,
        'category' => 'scanner',
        'paranoia' => 'medium',
        'explanation' => 'Detects common Acunetix scanner fingerprints.',
        'examples' => ['acunetix-product'],
        'false_positives' => ['Security testing dashboards'],
    ],
    [
        'id' => 'SCANNER_NIKTO',
        'type' => 'keyword',
        'pattern' => 'nikto',
        'score' => 25,
        'category' => 'scanner',
        'paranoia' => 'medium',
        'explanation' => 'Detects common Nikto scanner fingerprints.',
        'examples' => ['User-Agent: Nikto/2.5.0'],
        'false_positives' => ['Security tool documentation'],
    ],
    [
        'id' => 'WEBSHELL_C99',
        'type' => 'keyword',
        'pattern' => 'c99shell',
        'score' => 25,
        'category' => 'webshell',
        'paranoia' => 'medium',
        'explanation' => 'Detects common C99 webshell fragments.',
        'examples' => ['c99shell.php'],
        'false_positives' => ['Malware analysis content'],
    ],
    [
        'id' => 'WEBSHELL_EVAL_POST',
        'type' => 'keyword',
        'pattern' => 'eval($_post',
        'score' => 16,
        'category' => 'webshell',
        'paranoia' => 'high',
        'explanation' => 'Detects PHP webshell snippets that eval POST data.',
        'examples' => ['<?php eval($_POST["cmd"]); ?>'],
        'false_positives' => ['PHP security training content'],
    ],
    [
        'id' => 'WEBSHELL_SYSTEM_GET',
        'type' => 'keyword',
        'pattern' => 'system($_get',
        'score' => 16,
        'category' => 'webshell',
        'paranoia' => 'high',
        'explanation' => 'Detects PHP webshell snippets that pass GET data into system().',
        'examples' => ['<?php system($_GET["cmd"]); ?>'],
        'false_positives' => ['PHP security training content'],
    ],
    [
        'id' => 'PHP_ASSERT_CALL',
        'type' => 'keyword',
        'pattern' => 'assert(',
        'score' => 12,
        'category' => 'php_injection',
        'paranoia' => 'high',
        'explanation' => 'Marks PHP assert calls for bounded PHP injection confirmation.',
        'examples' => ['assert($_GET["cmd"])'],
        'false_positives' => ['PHP source-code education forms'],
    ],
    [
        'id' => 'LFI_TRAVERSAL_TOKEN',
        'type' => 'keyword',
        'pattern' => '../',
        'score' => 8,
        'category' => 'lfi',
        'paranoia' => 'medium',
        'explanation' => 'Marks directory traversal sequences for bounded LFI regex confirmation.',
        'examples' => ['../../../../etc/passwd'],
        'false_positives' => ['Relative paths in file management tools'],
    ],
    [
        'id' => 'RFI_HTTP_SCHEME',
        'type' => 'keyword',
        'pattern' => 'http://',
        'score' => 7,
        'category' => 'rfi',
        'paranoia' => 'strict',
        'explanation' => 'Marks remote HTTP URLs for strict-mode RFI regex confirmation.',
        'examples' => ['page=http://evil.example/shell.php'],
        'false_positives' => ['Legitimate URL parameters in strict mode'],
    ],
    [
        'id' => 'PROTOCOL_GOPHER_URL',
        'type' => 'keyword',
        'pattern' => 'gopher://',
        'score' => 18,
        'category' => 'protocol',
        'paranoia' => 'high',
        'explanation' => 'Detects gopher URLs commonly used in SSRF protocol abuse probes.',
        'examples' => ['url=gopher://127.0.0.1:6379/_INFO'],
        'false_positives' => ['Applications that intentionally accept legacy protocol URLs'],
    ],
    [
        'id' => 'UPLOAD_PHP_EXTENSION',
        'type' => 'keyword',
        'pattern' => '.php',
        'score' => 12,
        'category' => 'upload',
        'paranoia' => 'medium',
        'explanation' => 'Detects uploaded filenames containing PHP extensions.',
        'examples' => ['avatar.php'],
        'false_positives' => ['Projects that intentionally accept source code uploads'],
    ],
    [
        'id' => 'UPLOAD_PHTML_EXTENSION',
        'type' => 'keyword',
        'pattern' => '.phtml',
        'score' => 12,
        'category' => 'upload',
        'paranoia' => 'medium',
        'explanation' => 'Detects uploaded filenames containing PHTML extensions.',
        'examples' => ['template.phtml'],
        'false_positives' => ['Projects that intentionally accept source code uploads'],
    ],
    [
        'id' => 'UPLOAD_PHP_MIME',
        'type' => 'keyword',
        'pattern' => 'x-httpd-php',
        'score' => 10,
        'category' => 'upload',
        'paranoia' => 'medium',
        'explanation' => 'Detects client-supplied PHP upload MIME types.',
        'examples' => ['application/x-httpd-php'],
        'false_positives' => ['Developer tools or source-code upload workflows'],
    ],
    [
        'id' => 'SQL_BOOLEAN_OR',
        'type' => 'regex',
        'pattern' => '/\bor\b\s+\d+\s*=\s*\d+/i',
        'score' => 14,
        'category' => 'sqli',
        'paranoia' => 'strict',
        'requires' => [],
        'explanation' => 'Detects boolean SQL injection probes.',
        'examples' => ['or 1=1'],
        'false_positives' => ['Searches for literal SQL examples'],
        'benchmark' => 'Bounded keyword and digit classes; no nested quantifiers.',
    ],
    [
        'id' => 'SQL_UNION_FROM',
        'type' => 'regex',
        'pattern' => '/\bunion\b.{0,80}?\bselect\b.{0,120}?\bfrom\b/i',
        'score' => 18,
        'category' => 'sqli',
        'paranoia' => 'medium',
        'requires' => ['SQL_UNION_SELECT'],
        'explanation' => 'Detects bounded UNION SELECT FROM structures.',
        'examples' => ['union select password from users'],
        'false_positives' => ['SQL documentation'],
        'benchmark' => 'Bounded wildcards limit backtracking.',
    ],
    [
        'id' => 'XSS_TAG_EVENT',
        'type' => 'regex',
        'pattern' => '/<[^>]{0,120}\bon[a-z]{2,30}\s*=/i',
        'score' => 16,
        'category' => 'xss',
        'paranoia' => 'high',
        'requires' => ['XSS_EVENT_HANDLER'],
        'explanation' => 'Detects bounded HTML tag event handlers.',
        'examples' => ['<img src=x onerror=alert(1)>'],
        'false_positives' => ['HTML examples'],
        'benchmark' => 'Bounded tag scan avoids unbounded dot-star.',
    ],
    [
        'id' => 'RFI_REMOTE_SCRIPT',
        'type' => 'regex',
        'pattern' => '/(?:^|[?&=])https?:\/\/[^\s&]{1,160}\.(?:php[0-9]?|phtml|txt|dat)(?:[?&#]|$)/i',
        'score' => 16,
        'category' => 'rfi',
        'paranoia' => 'strict',
        'requires' => ['RFI_HTTP_SCHEME'],
        'explanation' => 'Detects strict-mode remote file inclusion probes targeting script-like resources.',
        'examples' => ['page=http://evil.example/shell.php'],
        'false_positives' => ['Applications that legitimately accept remote script URLs'],
        'benchmark' => 'Bounded host/path segment avoids unbounded wildcard scans.',
    ],
    [
        'id' => 'WEBSHELL_EVAL_POST_CALL',
        'type' => 'regex',
        'pattern' => '/\beval\s*\(\s*\$_post\s*\[[^\]]{1,80}\]\s*\)/i',
        'score' => 12,
        'category' => 'webshell',
        'paranoia' => 'high',
        'requires' => ['WEBSHELL_EVAL_POST'],
        'explanation' => 'Confirms bounded eval($_POST[...]) webshell execution snippets.',
        'examples' => ['<?php eval($_POST["cmd"]); ?>'],
        'false_positives' => ['PHP security training content'],
        'benchmark' => 'Bounded bracket expression avoids nested quantifiers.',
    ],
    [
        'id' => 'PHP_ASSERT_SUPERGLOBAL_CALL',
        'type' => 'regex',
        'pattern' => '/\bassert\s*\(\s*\$_(?:get|post|request|cookie)\s*\[[^\]]{1,80}\]\s*\)/i',
        'score' => 14,
        'category' => 'php_injection',
        'paranoia' => 'high',
        'requires' => ['PHP_ASSERT_CALL'],
        'explanation' => 'Confirms bounded assert($_GET/POST/REQUEST/COOKIE[...]) PHP injection snippets.',
        'examples' => ['assert($_GET["cmd"])'],
        'false_positives' => ['PHP security training content'],
        'benchmark' => 'Bounded bracket expression avoids nested quantifiers.',
    ],
    [
        'id' => 'WEBSHELL_SYSTEM_GET_CALL',
        'type' => 'regex',
        'pattern' => '/\bsystem\s*\(\s*\$_get\s*\[[^\]]{1,80}\]\s*\)/i',
        'score' => 12,
        'category' => 'webshell',
        'paranoia' => 'high',
        'requires' => ['WEBSHELL_SYSTEM_GET'],
        'explanation' => 'Confirms bounded system($_GET[...]) webshell execution snippets.',
        'examples' => ['<?php system($_GET["cmd"]); ?>'],
        'false_positives' => ['PHP security training content'],
        'benchmark' => 'Bounded bracket expression avoids nested quantifiers.',
    ],
    [
        'id' => 'LFI_TRAVERSAL_SENSITIVE_FILE',
        'type' => 'regex',
        'pattern' => '/(?:\.\.\/){1,8}(?:etc\/passwd|windows\/win\.ini)(?:$|[?&#\s])/i',
        'score' => 16,
        'category' => 'lfi',
        'paranoia' => 'medium',
        'requires' => ['LFI_TRAVERSAL_TOKEN'],
        'explanation' => 'Detects bounded path traversal attempts to sensitive OS files.',
        'examples' => ['../../../../etc/passwd', '../../windows/win.ini'],
        'false_positives' => ['Security training content or file-management tools'],
        'benchmark' => 'Traversal repetition is capped at eight path segments.',
    ],
    [
        'id' => 'UPLOAD_DOUBLE_EXTENSION_SCRIPT',
        'type' => 'regex',
        'pattern' => '/\.(?:php[0-9]?|phtml|phar)\.[a-z0-9]{1,8}\z/i',
        'score' => 16,
        'category' => 'upload',
        'paranoia' => 'medium',
        'requires' => ['UPLOAD_PHP_EXTENSION'],
        'explanation' => 'Detects upload evasion attempts using script extensions hidden before a final extension.',
        'examples' => ['avatar.php.jpg'],
        'false_positives' => ['Source-code archives or education uploads that intentionally permit PHP filenames'],
        'benchmark' => 'Anchored filename suffix check with bounded final extension length.',
    ],
];
