<?php

/*
 * Rule paranoia levels:
 *
 * low    - highest-confidence rules for apps with low false-positive tolerance
 * medium - default balanced rules
 * high   - more aggressive rules for apps that can tolerate more review/blocking
 * strict - most aggressive rules and edge-case probes
 *
 * Fireline runs rules at or below the configured paranoia_level.
 */

return [
    [
        'id' => 'SQL_UNION_SELECT',
        'type' => 'keyword',
        'pattern' => 'union select',
        'score' => 12,
        'category' => 'sqli',
        'paranoia' => 'low',
        'explanation' => 'Detects UNION SELECT SQL injection attempts.',
        'examples' => ['1 union select password from users'],
        'false_positives' => ['Documentation discussing UNION SELECT syntax'],
    ],
    [
        'id' => 'SQL_INFORMATION_SCHEMA',
        'type' => 'keyword',
        'pattern' => 'information_schema',
        'score' => 10,
        'category' => 'sqli',
        'paranoia' => 'medium',
        'explanation' => 'Detects database schema enumeration attempts.',
        'examples' => ['select table_name from information_schema.tables'],
        'false_positives' => ['Database administration tools'],
    ],
    [
        'id' => 'SQL_SLEEP',
        'type' => 'keyword',
        'pattern' => 'sleep(',
        'score' => 10,
        'category' => 'sqli',
        'paranoia' => 'medium',
        'explanation' => 'Detects time-based SQL injection probes.',
        'examples' => ['sleep(5)'],
        'false_positives' => ['Code snippets submitted in developer tools'],
    ],
    [
        'id' => 'XSS_SCRIPT_TAG',
        'type' => 'keyword',
        'pattern' => '<script',
        'score' => 20,
        'category' => 'xss',
        'paranoia' => 'low',
        'explanation' => 'Detects script tag injection.',
        'examples' => ['<script>alert(1)</script>'],
        'false_positives' => ['HTML tutorial submissions'],
    ],
    [
        'id' => 'XSS_JAVASCRIPT_SCHEME',
        'type' => 'keyword',
        'pattern' => 'javascript:',
        'score' => 12,
        'category' => 'xss',
        'paranoia' => 'medium',
        'explanation' => 'Detects JavaScript URL scheme injection.',
        'examples' => ['javascript:alert(1)'],
        'false_positives' => ['Documentation about JavaScript URLs'],
    ],
    [
        'id' => 'XSS_EVENT_HANDLER',
        'type' => 'keyword',
        'pattern' => 'onerror=',
        'score' => 12,
        'category' => 'xss',
        'paranoia' => 'high',
        'explanation' => 'Detects inline browser event handler payloads.',
        'examples' => ['<img src=x onerror=alert(1)>'],
        'false_positives' => ['HTML examples'],
    ],
    [
        'id' => 'SHELL_BIN_SH',
        'type' => 'keyword',
        'pattern' => '/bin/sh',
        'score' => 14,
        'category' => 'shell',
        'paranoia' => 'low',
        'explanation' => 'Detects shell execution probes.',
        'examples' => ['cmd=/bin/sh'],
        'false_positives' => ['Server administration forms'],
    ],
    [
        'id' => 'LFI_ETC_PASSWD',
        'type' => 'keyword',
        'pattern' => '/etc/passwd',
        'score' => 14,
        'category' => 'lfi',
        'paranoia' => 'low',
        'explanation' => 'Detects common Linux file disclosure probes.',
        'examples' => ['file=/etc/passwd'],
        'false_positives' => ['Security training content'],
    ],
    [
        'id' => 'SQL_BOOLEAN_OR',
        'type' => 'regex',
        'pattern' => '/\bor\b\s+\d+\s*=\s*\d+/i',
        'score' => 14,
        'category' => 'sqli',
        'paranoia' => 'strict',
        'requires' => [],
        'explanation' => 'Detects boolean SQL injection probes.',
        'examples' => ['or 1=1'],
        'false_positives' => ['Searches for literal SQL examples'],
        'benchmark' => 'Bounded keyword and digit classes; no nested quantifiers.',
    ],
    [
        'id' => 'SQL_UNION_FROM',
        'type' => 'regex',
        'pattern' => '/\bunion\b.{0,80}?\bselect\b.{0,120}?\bfrom\b/i',
        'score' => 18,
        'category' => 'sqli',
        'paranoia' => 'medium',
        'requires' => ['SQL_UNION_SELECT'],
        'explanation' => 'Detects bounded UNION SELECT FROM structures.',
        'examples' => ['union select password from users'],
        'false_positives' => ['SQL documentation'],
        'benchmark' => 'Bounded wildcards limit backtracking.',
    ],
    [
        'id' => 'XSS_TAG_EVENT',
        'type' => 'regex',
        'pattern' => '/<[^>]{0,120}\bon[a-z]{2,30}\s*=/i',
        'score' => 16,
        'category' => 'xss',
        'paranoia' => 'high',
        'requires' => ['XSS_EVENT_HANDLER'],
        'explanation' => 'Detects bounded HTML tag event handlers.',
        'examples' => ['<img src=x onerror=alert(1)>'],
        'false_positives' => ['HTML examples'],
        'benchmark' => 'Bounded tag scan avoids unbounded dot-star.',
    ],
];
